# Project information
site_name: 运维笔记
site_url: https://dengyouf.github.io/books
site_author: dengyouf
site_description: >-
  使用 Markdown 编写文档，仅需几分钟即可构建一个专业的静态网站 —— 支持全文搜索、灵活定制，覆盖 60 多种语言，兼容所有设备。

# Repository
repo_name: dengyouf/books
repo_url: https://github.com/dengyouf/books

# Copyright
copyright: Copyright &copy; 2016 - 2025 Martin Donath

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dengyouf
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/dengyouf/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  # - 主页: index.md
  - Storage:
    - Ceph:
        - Installation:
            - ceph-deploy:
                - nautilus: "storage/ceph.md"
        - Management:
            - osd: "storage/osd.md"
            - auth: "storage/auth.md"
            - rbd: "storage/rbd.md"
            - rgw: "storage/rgw.md"
            - cephfs: "storage/cephfs.md"
            - cluster: "storage/cluster.md"
  - DevOps:
      - Installation:
          - gitlab: devops/gitlab.md
          - jenkins: devops/jenkins.md
          - nexus: devops/nexus.md
          - sonarqube: devops/sonar.md
  - Monitoring:
    - PrometheusStack:
        - prometheus: "monitoring/prometheus.md"
        - node exporter: "monitoring/node-exporter.md"
        - alertmanager: "monitoring/alertmanager.md"
        - blackbox export: "monitoring/blackbox-exporter.md"
        - grafana: "monitoring/grafana.md"

  - Kubernetes:
    - Installation:
        - kubeadm:
            - v1.30.3: "k8s/kubeadm-v1.30.12.md"
    - Helm:
      - helm: "k8s/helm.md"
    - Kustomize:
      - Kustomize: "k8s/kustomize.md"
    - Ingress:
        - ingress-nginx: "k8s/ingress-nginx.md"
    - Kube-prometheus:
        - kube-prometheus: "k8s/kube-prometheus.md"
    - Storage:
        - nfs-subdir-external-provisioner: "k8s/nfs-subdir-external-provisioner.md"

    - Private Registry:
        - habor:
            - v2.14.0: "k8s/harbor.md"


