---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wp
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: http-3306
    protocol: TCP
    port: 3306
    targetPort: 3306
