apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-monitoring-sa
  namespace: kube-system
  labels:
    app: zabbix-monitoring
    version: "1.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-monitoring-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: zabbix-monitoring-sa
type: kubernetes.io/service-account-token

