apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zabbix-monitoring-binding
  labels:
    app: zabbix-monitoring
    version: "1.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zabbix-monitoring-role
subjects:
  - kind: ServiceAccount
    name: zabbix-monitoring-sa
    namespace: kube-system

